<?php declare(strict_types=1);

/**
 * Class-RedisCache.php
 *
 * @package Redis Cache
 * @link https://github.com/dragomano/Redis-Cache-for-SMF
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2022-2024 Bugo
 * @license https://opensource.org/licenses/BSD-3-Clause The 3-Clause BSD License
 *
 * @version 0.4
 */

if (!defined('SMF'))
	die('No direct access...');

/**
 * Generated by Simple Mod Maker
 */
final class RedisCache
{
	public function hooks(): void
	{
		add_integration_function('integrate_server_settings', __CLASS__ . '::serverSettings#', false, __FILE__);
		add_integration_function('integrate_update_settings_file', __CLASS__ . '::updateSettingsFile#', false, __FILE__);
	}

	/**
	 * @hook integrate_server_settings
	 */
	public function serverSettings(): void
	{
		loadLanguage('RedisCache/');
	}

	/**
	 * @hook integrate_update_settings_file
	 */
	public function updateSettingsFile(array &$settings_defs): void
	{
		$settings_defs['cache_redis'] = [
			'text' => implode("\n", [
				'/**',
				' * This is only used for Redis. Should be a string of \'server:port,server:port\'',
				' *',
				' * @var string',
				' */',
			]),
			'default' => '127.0.0.1:6379',
			'type' => 'string'
		];

		$settings_defs['cache_redis_username'] = [
			'text' => implode("\n", [
				'/**',
				' * Username to connect with Redis (optional)',
				' *',
				' * @var string',
				' */',
			]),
			'default' => '',
			'type' => 'string'
		];

		$settings_defs['cache_redis_password'] = [
			'text' => implode("\n", [
				'/**',
				' * Password to connect with Redis (optional)',
				' *',
				' * @var string',
				' */',
			]),
			'default' => '',
			'type' => 'string',
			'is_password' => true,
		];
	}
}
